library(tidyverse)

# Generated by Claude Sonnet 4.6 for 
# "Global Hub Analysis & Stochastic Modeling" document

# 1. Load the CSV
calcium_raw <- read.csv("calcium.csv")

# 2. Separate into Null and Diet/Exercise data frames
null_df <- calcium_raw[, 1:4]
diet_df  <- calcium_raw[, 5:8]

# 3. Standardize column names and add subject IDs, then pivot to long format
colnames(null_df) <- c("Initial", "Yr1", "Yr2", "Yr3")
colnames(diet_df) <- c("Initial", "Yr1", "Yr2", "Yr3")

null_df$Subject <- 1:nrow(null_df)
diet_df$Subject <- 1:nrow(diet_df)

null_long <- null_df |>
  pivot_longer(
    cols      = c("Initial", "Yr1", "Yr2", "Yr3"),
    names_to  = "Year",
    values_to = "Calcium"
  )

diet_long <- diet_df |>
  pivot_longer(
    cols      = c("Initial", "Yr1", "Yr2", "Yr3"),
    names_to  = "Year",
    values_to = "Calcium"
  )

# 4. Add treatment group labels and combine
null_long$Treatment <- "Null"
diet_long$Treatment <- "Diet/Exercise"

combined_df <- bind_rows(null_long, diet_long)

# Re-order Year factor so the x-axis displays chronologically
combined_df$Year <- factor(
  combined_df$Year,
  levels = c("Initial", "Yr1", "Yr2", "Yr3"),
  labels = c("Initial", "Year 1", "Year 2", "Year 3")
)

# 5. Spaghetti plot with group mean overlay
ggplot(combined_df, aes(x = Year, y = Calcium, group = interaction(Subject, Treatment), color = Treatment)) +
  
  # Individual subject trajectories (thin, semi-transparent)
  geom_line(alpha = 0.3, linewidth = 0.5) +
  geom_point(alpha = 0.3, size = 1.2) +
  
  # Group mean trajectories (bold overlay)
  stat_summary(
    aes(group = Treatment),
    fun      = mean,
    geom     = "line",
    linewidth = 1.8,
    linetype  = "solid"
  ) +
  stat_summary(
    aes(group = Treatment),
    fun   = mean,
    geom  = "point",
    size  = 4,
    shape = 18
  ) +
  
  # Styling
  scale_color_manual(values = c("Null" = "#619CFF", "Diet/Exercise" = "#F8766D")) +
  labs(
    title    = "Ulnar Calcium Measurements Over Time by Treatment Group",
    subtitle = "Thin lines = individual subjects | Bold lines = group mean",
    x        = "Time Point",
    y        = "Calcium (units)",
    color    = "Treatment Group"
  ) +
  theme_bw(base_size = 13) +
  theme(
    plot.title    = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "grey40"),
    legend.position = "top"
  )
